FORMAT: 1A

# Loyalty Points System API
This API allows customers create accounts, login, earn points for purchases, and redeem those points for rewards.

<!-- include(auth.apib) -->
<!-- include(products.apib) -->
<!-- include(points.apib) -->
<!-- include(transaction-history.apib) -->
<!-- include(admins/admins.apib) -->