## Data Structures

### ResetPasswordData
+ new_password: yournewpassword (required)
+ confirm_password: yournewpassword (required)

# Group Reset Password
Endpoints to reset a user's forgotten password

## Forgot Password [/api/auth/forgot-password]
Send password reset email to the requesting user email 

### Forgot password [POST]
+ Request with Body (application/json)

    + Attributes
        + email: user@example.com (required)

+ Response 200 (application/json)

    + Attributes
        + status: success (required)
        + message: We sent an email with a reset password code to user-email@example.com  (required)
       
+ Response 400

    + Attributes
        + status: error (required)
        + message: error-msg
        
+ Response 404

    + Attributes
        + status: fail (required)
        + message: User not found (required)

+ Response 500

    + Attributes
        + status: fail (required)
        + message: Failed to retrieve user (required)

## Reset Password [/api/auth/reset-password/{resetToken}]
Reset user's password

### Reset password [PATCH]

+ Parameters
    + resetToken (string)  ... user's password reset token

+ Request with Body (application/json)

    + Attributes(ResetPasswordData)

+ Response 200 (application/json)

    + Attributes
        + status: success (required)
        + message: Password reset successful (required)
       
+ Response 400

    + Attributes
        + status: fail (required)
        + message: error-msg (required)
